### ISSUE TITLE
Login to Kibana

### ISSUE THREAD

**Issue by benzionyunger** [boranx/docker-zap-elk#3]
I tried running your project, but Kibana doesn't recognize the default 'kibana' username or 'changeme' password. Can you please document the default login settings?

**Comment by boranx** [comment]
Hi,

Thanks for the issue.

The default username and password have already documented in Readme in that part:

```* Kibana is running on port 5601. just browse : http://localhost:5601  (username: elastic, pass: changeme)```

If you try ```elastic```,```changeme```, the login should be succeeded.

Thanks,
